# Generated by Django 5.2.4 on 2025-10-30 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_posts_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='title',
        ),
    ]
