# Generated by Django 5.2.4 on 2025-10-31 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_posts_creator_alter_comment_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='creator',
            field=models.CharField(max_length=50),
        ),
    ]
