# Generated by Django 5.2.4 on 2025-11-06 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0009_post_likes_alter_comment_post_delete_posts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Likes',
            new_name='Like',
        ),
    ]
