# Generated by Django 5.2.4 on 2025-11-06 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0010_rename_likes_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='creator_id',
            new_name='creator',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='post_id',
            new_name='post',
        ),
    ]
